### ISSUE TITLE
Performance vs. Alternative Implementations

### ISSUE THREAD

**Issue by lewisfogden** [lewisfogden/heavylight#2]
Heavylight generally selects simplicity of coding over performance, in particular using Caching classes to store results adds some overhead vs. alternatives.

Directly using dictionaries (example below) removes quite a bit of this overhead but much more boilerplate code is needed. i.e. manual stores for each variable need to be initialised and then updated.

Version using HeavyLight:
```
from heavylight import Model

class Policy(Model):
    def num_pols(self, t):
            if t == 0:
                return 1
            else:
                return self.num_pols(t - 1) - self.num_deaths(t - 1)
            
    def num_deaths(self, t):
            return self.num_pols(t) * 0.01

def run_pol():
    p = Policy(do_run=True, proj_len=400)
    return p.num_pols(399)
```

Version Using Dictionaries - runs faster but much less readable:
```python
class Policy:
    def __init__(self, proj_len: int):
        self.proj_len = proj_len
        self._v1 = {}
        self._v2 = {}
        
    def num_pols(self, t):     #_v1
        if t in self._v1:
            return self._v1[t]
        else:
            if t == 0:
                value = 1
            else:
                value = self.num_pols(t - 1) - self.num_deaths(t - 1)
            self._v1[t] = value
            return value
        
    def num_deaths(self, t):     #_v2
        if t in self._v2:
            return self._v2[t]
        else:
            value = self.num_pols(t) * 0.01
            self._v2[t] = value
            return value

def run_pol():
    p = Policy(400)
    return p.num_pols(399)
```

**Comment by lewisfogden** [comment]
Rough performance below:

memo_hl is the heavylight version, memo_dict is the dictionary version (quite a difference for this simple model).  cvect_memo is a test version written in cython (ran faster but I'm still working out how vectors/arrays work in cython).

![image](https://github.com/lewisfogden/heavylight/assets/8605587/6c31592b-9a21-470b-8a7e-f2919744cd8d)

**Comment by MatthewCaseres** [comment]
Added Heavylight to benchmarks repo that I manage, and it held up fine. https://github.com/actuarialopensource/benchmarks

Closing this in favor of issues to be opened under benchmarks repository.
