### ISSUE TITLE
method level aggregation on LightModel

### ISSUE THREAD

**Issue by MatthewCaseres** [lewisfogden/heavylight#20]
The LightModel currently aggregates all methods using the storage function. This is not practical because some functions might return different data types, it becomes messy and we end up having if statements and such.

So try to use decorators to apply storage functions at the method level. For benchmarking purposes, this allows a reduction in the number of floating point operations used to calculate results.

**Comment by lewisfogden** [comment]
From a practical perspective, people want to see different outputs from the model for different purposes (e.g. someone might everything, someone might just want the premiums and claims, so maybe a `targets = [<list of methods to output>]` approach might work?

(If this is embedded in the model, then users would need to change the model to change what is output, which hurts auditability)

**Comment by MatthewCaseres** [comment]
Edit a million: Storage function will continue working like it has, it will have a sensible default, the method level decorators will still be implemented as they are necessary for benchmarking

**Comment by MatthewCaseres** [comment]
closed via #22
