### ISSUE TITLE
Release 1.0.6

### ISSUE THREAD

**Issue by lewisfogden** [lewisfogden/heavylight#23]

**Comment by lewisfogden** [comment]
@MatthewCaseres  Think we're ready for releasing v1.0.6 to pypi soon, capturing all the latest changes.

- [ ] I'm adding a template/example generator 'make_example' which can set up a few examples for users. (I'm going to use them for demos/getting started)
- [ ] I've added you as an author in pyproject.toml - please set email if you want it :)

Anything else to add?   (this is in branch dev_core_docs, I'll merge soon)

**Comment by MatthewCaseres** [comment]
I'd like to close out #9 and start using proper release notes but I can't upload to pypi so it seems like you'll have to do that one?

Another note is that we are not abiding by the rules of semantic versioning. If you had not released v1.0.0 then we would not be breaking the rules. And we still might ship more breaking changes (unless we are certain we won't) so it is a funny spot to be in https://semver.org/. This is more of a comment, I have no idea what we are supposed to do except keep iterating on the design until we are very confident and a 2.0.0 is released and we promise API stability.

**Comment by lewisfogden** [comment]
I've still to read (and understand) the automated building, I've got hatch set up which does it all on my own machine for now.

**SemVer**: Agree - I wasn't aware of semantic versioning when I first released.  I think we're pretty safe to go for it as 1.0.6 and then run semver on that going forward:
- not many people using the library yet (I suspect just me & you)
- breaking changes aren't really breaking, e.g. I've got a Warning on `do_run`, and `.ToDataFrame()` isn't removed yet in favour of `.df` property.
- can caveat in readme.

API wise, it feels like I've got what I want in `heavylight.Model`, we probably need to look at consistency between that and the optimised versions though.  `heavylight.Table` still needs a bit of thinking on API - for now I'm leaving it as opinionated on having metadata encoded in the column names (`|int`, etc.)

(I could yank the current versions from pypi, and put in at 0.2.0 but it might cause other problems.)

**Comment by lewisfogden** [comment]
I've put in PR but tests fail for 3.8, 3.9 due to `path: str|pathlib.Path` not being recognised.  I'll probably just drop the type hints here for now.  Need to sleep now, so probably easier to merge and then fix in main.

**Comment by MatthewCaseres** [comment]
No rush lets wait on merging for another day, type signatures in user facing functions is usually nice. gives me some time to review

**Comment by MatthewCaseres** [comment]
I went ahead and merged it after writing a test and changing some code style but not the substance

**Comment by lewisfogden** [comment]
Thank you!  Would you like to add your email address to pyproject.toml (https://github.com/lewisfogden/heavylight/blob/main/pyproject.toml) and then I'll publish to pypi?

**Comment by MatthewCaseres** [comment]
its changed

**Comment by lewisfogden** [comment]
Fab - we're live with 1.0.6:  https://pypi.org/project/heavylight/1.0.6/ (Just running post-live checks now using a new colab environment)

**Comment by lewisfogden** [comment]
All good!
