### ISSUE TITLE
Colab Notebook doesn't run?

### ISSUE THREAD

**Issue by alecloudenback** [lewisfogden/heavylight#36]
Was trying to see what was going on with [this notebook](https://www.linkedin.com/feed/update/urn:li:activity:7181911912819953665?utm_source=share&utm_medium=member_desktop) but running all doesn't work with the errors below:

<img width="1564" alt="image" src="https://github.com/lewisfogden/heavylight/assets/711879/b898f485-396d-4ea7-9268-69c4b73dc185">

**Comment by lewisfogden** [comment]
Unfortunately I think Matthew accidentally wrote over the notebook:

<img width="1056" alt="Screenshot 2024-04-10 at 21 07 38" src="https://github.com/lewisfogden/heavylight/assets/8605587/69e39ca6-2f78-4d77-9129-72ffe8917c4e">

He might be able to restore an older version, I'm not sure how good CoLab's history is.

**Comment by MatthewCaseres** [comment]
Yeah I'll revert the changes and get back to you, apologies @alecloudenback

**Comment by MatthewCaseres** [comment]
Ok changes are reverted. I couldn't get the A100 again, colab only wants me to have a V100 :(. Trying to find a reliable provider of A100 - H100 GPU for benchmarking activities.
